name: setup
description: standard job setup
runs:
  using: "composite"
  steps:
    - name: Configure direnv
      uses: HatsuneMiku3939/direnv-action@v1

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Node cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: ${{ github.workflow}}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
        aws-region: us-east-1
        role-duration-seconds: 10800
