service: ${self:custom.project}-alerts

frameworkVersion: "3"

package:
  individually: true

plugins:
  - "@stratiformdigital/serverless-iam-helper"
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-s3-security-helper"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: infra
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/iam/path, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/iam/path}
      permissionsBoundary: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/iam/permissionsBoundary, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/iam/permissionsBoundary}

custom:
  project: ${env:PROJECT}
  serverlessTerminationProtection:
    stages: # Apply CloudFormation termination protection for these stages
      - infra
  GitHubIdentityProviderArn: "arn:aws:iam::${aws:accountId}:oidc-provider/token.actions.githubusercontent.com"
  ManagedPolicyARNs:
    - arn:aws:iam::${aws:accountId}:policy/ADO-Restriction-Policy
    - arn:aws:iam::${aws:accountId}:policy/CMSApprovedAWSServices
    - arn:aws:iam::aws:policy/AdministratorAccess
  SubjectClaimFilters: "repo:Enterprise-CMCS/macpro-base-template:*"
resources:
  Resources:
    GitHubActionsServiceRole:
      Type: AWS::IAM::Role
      Properties:
        MaxSessionDuration: 10800
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: RoleForGitHubActions
              Effect: Allow
              Principal:
                Federated: ${self:custom.GitHubIdentityProviderArn}
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "token.actions.githubusercontent.com:aud": sts.amazonaws.com
                StringLike:
                  "token.actions.githubusercontent.com:sub": ${self:custom.SubjectClaimFilters}
        Description: Service Role for use in GitHub Actions
        ManagedPolicyArns: ${self:custom.ManagedPolicyARNs}
  Outputs:
    ServiceRoleARN:
      Description: arn of service role for use in GitHub actions
      Value: !GetAtt GitHubActionsServiceRole.Arn
