on:
  pull_request:
    types: [opened, edited]
name: hithub to jira2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_BASE_URL: https://qmacbis.atlassian.net
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
      - name: get jira ticket
        run: echo "::set-output name=TICKET_NAME::$(echo '${{ github.event.pull_request.body }}' | grep -oE '\b[A-Z]+[0-9]+-[0-9]+\b')"
        id: get_t
      - name: Comment on issue
        #uses: atlassian/gajira-comment@v3
        env:
          GH_EVENT: ${{ toJson(github) }}
        run: |
          if [ -n ${{ steps.get_t.outputs.TICKET_NAME }} ]; then
          for jiraTicket in "${{ steps.get_t.outputs.TICKET_NAME }}"
          do
            curl --request POST \
              --url "https://${{ env.JIRA_BASE_URL }}/rest/api/2/issue/${jiraTicket}/comment" \
              --user "${{ env.JIRA_USER_EMAIL }}:${{ env.JIRA_PASSWORD }}" \
              --header "Content-Type: application/json" \
              --data "{\"body\": \"${{ github.event_name }} ${{ github.event.pull_request._links.html.href }}\"}"
          done
          else
          echo "no ticket found"
          fi
