on:
  pull_request:
    types: [opened, edited]
name: Jira Issue Commenter

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
      - name: get jira ticket
        id: get_t
        run: |
          body='${{ github.event.pull_request.body }}'
          body_esc="${body@Q}"
          echo $body_esc
          issues=(`echo $body_esc | grep -oe "\b${JIRA_BASE_URL}[^ ]*\b"`)
          # issueString=$(printf ",%s" "${issues[@]}")
          # issueString=${issueString:1}
          # echo "ISSUESTRING=$issueString" >> $GITHUB_OUTPUT
          # echo "DEBUG"
          # cat $GITHUB_OUTPUT
        env:
          JIRA_BASE_URL: https://qmacbis.atlassian.net
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: https://qmacbis.atlassian.net
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
      # - name: get jira ticket
      #   run: echo "::set-output name=TICKET_NAME::$(echo '${{ github.event.pull_request.body }}' | grep -oE '\b[A-Z]+[0-9]+-[0-9]+\b')"
      #   id: get_t
      - name: Comment on issue
        uses: atlassian/gajira-comment@v3
        env:
          GH_EVENT: ${{ toJson(github) }}
        with:
          issue: ${{ steps.get_t.outputs.TICKET_NAME }}
          comment: ${{ github.event_name }} ${{ github.event.pull_request._links.html.href }}
