on:
  pull_request:
    types: [opened, edited]
name: Jira Issue Commenter

jobs:
  search:
    runs-on: ubuntu-latest
    name: Search PR for mentioned Jira Issues
    if: secrets.JIRA_TOKEN != ''
    outputs:
      issues: ${{ steps.search.outputs.issues }}
    steps:
      - name: find issues
        id: search
        env:
          JIRA_BASE_URL: https://qmacbis.atlassian.net/browse/
        run: |
          body='${{ github.event.pull_request.body }}'
          cat <<< "${body@Q}" > .tmp.body.txt
          issues=(`cat .tmp.body.txt | grep -oP "(?<=${JIRA_BASE_URL})[A-Z]+\d+-\d+" || true`)
          issueJson=`jq -c -n '$ARGS.positional' --args "${issues[@]}"`
          echo "issues=$issueJson" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  comment:
    runs-on: ubuntu-latest
    name: Comment on Jira Issues
    needs: search
    if: needs.search.outputs.issues != '[]'
    strategy:
      matrix:
        value: ${{fromJson(needs.search.outputs.issues)}}
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_BASE_URL: https://qmacbis.atlassian.net
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USERNAME }}
      - name: Comment on issue
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ matrix.value }}
          comment: ${{ github.event_name }} ${{ github.event.pull_request._links.html.href }}
