name: Security Hub Jira Sync

on:
  # schedule:
  #   - cron: "0 14-23/2 * * *"
  workflow_dispatch:

jobs:
  security-hub-jira-sync:
    name: Security Hub Jira Sync
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure direnv
        uses: HatsuneMiku3939/direnv-action@v1

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Node cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-duration-seconds: 10800

      - name: Invoke Security Hub Jira Sync
        id: runningStages
        env:
          JIRA_HOST: qmacbis.atlassian.net
          JIRA_USERNAME: xxx
          JIRA_TOKEN: xxx
          JIRA_PROJECT: OY2
          JIRA_CLOSED_STATUSES: "Done"
          PROJECT: cms-bigmac
        run: |
          npm i -g ts-node
          ts-node src/run-sync.ts