name: Workspace Setup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * SUN"
  push:
    branches:
      - "docsupdate"

concurrency:
  group: ${{ github.ref_name }}-test-ws-setup

jobs:
  test:
    runs-on: macos-12
    timeout-minutes: 30 # MacOS runners are more expensive than linux, so we want to be sure to stop any stuck builds.
    environment:
      name: test-ws-setup
    env:
      STAGE_NAME: test-ws-setup
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # GitHub Actions does not honor the direnv bash hook, so we explicitly configure it here
      - name: Configure direnv
        uses: HatsuneMiku3939/direnv-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-duration-seconds: 10800

      - name: Run workspace setup
        run: |
          sh docs/assets/setup.sh

      - name: Run nvm install
        run: |
          source /tmp/rcfile
          nvm install

      - name: Test install
        run: |
          source /tmp/rcfile
          nvm use
          run install

      - name: Test docs
        run: |
          source /tmp/rcfile
          nvm use
          colima start
          run docs & sleep 30
          docker ps | grep jekyll
          run docs --stop
          colima stop

      - name: Test deploy
        run: |
          source /tmp/rcfile
          nvm use
          run deploy --stage $STAGE_NAME

      - name: Test destroy
        run: |
          source /tmp/rcfile
          nvm use
          run destroy --stage $STAGE_NAME --verify false --wait false

      # UNCOMMENT THIS BEFORE MERGE
      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   if: env.SLACK_WEBHOOK != '' && failure()
      #   env:
      #     SLACK_COLOR: ${{job.status}}
      #     SLACK_ICON: https://github.com/Enterprise-CMCS.png?size=48
      #     SLACK_TITLE: Failure
      #     SLACK_USERNAME: ${{ github.repository }} - ${{job.status}}
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
